FROM ubuntu

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

COPY src/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requiments.txt

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]
